#!/bin/bash

# ============================================
# COMANDOS RÁPIDOS PARA SSH NA VPS
# ============================================

echo "🔐 ACESSO SSH - AVALIASOLAR VPS"
echo "================================"
echo ""
echo "IP da sua máquina local: 192.168.0.109"
echo ""
echo "⚠️  IMPORTANTE: Use o IP PÚBLICO da sua VPS, não o local!"
echo ""
echo "📋 Comandos para copiar arquivos para a VPS:"
echo ""
echo "# 1. Copiar docker-compose.yml"
echo "scp docker-compose.yml root@SEU_IP_VPS:/root/AB0-1/"
echo ""
echo "# 2. Copiar .env.production do frontend"
echo "scp AB0-1-front/.env.production root@SEU_IP_VPS:/root/AB0-1/AB0-1-front/"
echo ""
echo "# 3. Copiar scripts de deploy e validação"
echo "scp deploy-fix.sh root@SEU_IP_VPS:/root/AB0-1/"
echo "scp validate-config.sh root@SEU_IP_VPS:/root/AB0-1/"
echo ""
echo "# 4. OU copiar tudo de uma vez"
echo "scp docker-compose.yml AB0-1-front/.env.production deploy-fix.sh validate-config.sh root@SEU_IP_VPS:/root/AB0-1/"
echo ""
echo "================================"
echo ""
echo "📋 Comandos para executar NA VPS (após SSH):"
echo ""
echo "# Conectar via SSH"
echo "ssh root@SEU_IP_VPS"
echo ""
echo "# Depois de conectado, executar:"
echo "cd /root/AB0-1"
echo "chmod +x deploy-fix.sh validate-config.sh"
echo "./deploy-fix.sh"
echo "./validate-config.sh"
echo ""
echo "================================"
echo ""
echo "🌐 Se você estiver na mesma rede local da VPS:"
echo "ssh root@192.168.0.109"
echo ""
echo "🌍 Se a VPS estiver na nuvem (DigitalOcean, AWS, etc):"
echo "Você precisa do IP PÚBLICO da VPS (exemplo: 64.225.59.107)"
echo ""
echo "================================"
echo ""
echo "💡 DICA: Para encontrar o IP da VPS:"
echo "  - DigitalOcean: Painel > Droplets > Ver IP"
echo "  - AWS: EC2 Console > Instances > IP público"
echo "  - Google Cloud: VM Instances > External IP"
echo ""
echo "================================"
echo ""
echo "🔑 Se precisar de senha ou chave SSH:"
echo "  - Senha: Você deve ter recebido por email ao criar a VPS"
echo "  - Chave SSH: ssh -i ~/.ssh/sua_chave.pem root@IP_VPS"
echo ""
echo "================================"
echo ""
echo "📝 Exemplo completo de deploy:"
echo ""
echo "# 1. Copiar arquivos do seu Mac para a VPS"
echo 'scp -r docker-compose.yml AB0-1-front/.env.production deploy-fix.sh validate-config.sh root@IP_VPS:/root/AB0-1/'
echo ""
echo "# 2. Conectar na VPS"
echo "ssh root@IP_VPS"
echo ""
echo "# 3. Executar deploy"
echo "cd /root/AB0-1"
echo "chmod +x deploy-fix.sh validate-config.sh"
echo "./deploy-fix.sh"
echo ""
echo "# 4. Validar"
echo "./validate-config.sh"
echo ""
echo "================================"
