# Configuration file for New Relic APM
common: &default_settings
  license_key: '<%= ENV["NEW_RELIC_LICENSE_KEY"] %>'
  app_name: <%= ENV["NEW_RELIC_APP_NAME"] || "Avalia Solar (Produção)" %>
  monitor_mode: true
  developer_mode: false
  log_level: info
  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
  error_collector:
    enabled: true
    ignore_classes:
      - "ActionController::RoutingError"

production:
  <<: *default_settings

development:
  <<: *default_settings
  monitor_mode: false

test:
  <<: *default_settings
  monitor_mode: false
