# frozen_string_literal: true

class CreatePlatformEventsPartitioned < ActiveRecord::Migration[7.0]
  def up
    is_pg = ActiveRecord::Base.connection.adapter_name =~ /postgre/i

    if is_pg
      execute <<~SQL
        CREATE TABLE platform_events (
          id bigint GENERATED BY DEFAULT AS IDENTITY,
          event_id text NOT NULL,
          event_type text NOT NULL,
          schema_version integer DEFAULT 1,
          source text,
          anonymous_id text,
          session_id text,
          user_id bigint,
          company_id bigint,
          subject_type text,
          subject_id bigint,
          payload jsonb DEFAULT '{}',
          context jsonb DEFAULT '{}',
          occurred_at timestamptz NOT NULL,
          created_at timestamptz NOT NULL DEFAULT now()
        ) PARTITION BY RANGE (occurred_at);

        CREATE INDEX idx_platform_events_type_time ON platform_events (event_type, occurred_at DESC);
        CREATE INDEX idx_platform_events_brin_time ON platform_events USING BRIN (occurred_at);
        CREATE INDEX idx_platform_events_event_id ON platform_events (event_id);

        CREATE OR REPLACE FUNCTION create_platform_events_partition(target_date timestamptz)
        RETURNS text AS $$
        DECLARE
            start_date timestamptz := date_trunc('month', target_date);
            end_date timestamptz := start_date + interval '1 month';
            partition_name text := 'platform_events_y' || to_char(start_date, 'YYYY') || 'm' || to_char(start_date, 'MM');
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_class c 
                JOIN pg_namespace n ON n.oid = c.relnamespace 
                WHERE c.relname = partition_name 
                AND n.nspname = ANY(current_schemas(false))
            ) THEN
                EXECUTE format('CREATE TABLE %I PARTITION OF platform_events FOR VALUES FROM (%L) TO (%L)', partition_name, start_date, end_date);
                RETURN partition_name;
            END IF;
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;

        SELECT create_platform_events_partition(now());
        SELECT create_platform_events_partition(now() + interval '1 month');
        SELECT create_platform_events_partition(now() + interval '2 months');
      SQL
    else
      # Standard table for SQLite
      create_table :platform_events, if_not_exists: true do |t|
        t.text :event_id, null: false
        t.text :event_type, null: false
        t.integer :schema_version, default: 1
        t.text :source
        t.text :anonymous_id
        t.text :session_id
        t.bigint :user_id
        t.bigint :company_id
        t.text :subject_type
        t.bigint :subject_id
        t.json :payload, default: {}
        t.json :context, default: {}
        t.datetime :occurred_at, null: false
        t.datetime :created_at, null: false, default: -> { 'CURRENT_TIMESTAMP' }
      end
      add_index :platform_events, [:event_type, :occurred_at]
      add_index :platform_events, :event_id
    end
  end

  def down
    drop_table :platform_events if table_exists?(:platform_events)
  end
end
