class CreatePlatformEventsPartitioned < ActiveRecord::Migration[7.0]
  def up
    return unless ActiveRecord::Base.connection.adapter_name =~ /postgre/i

    execute <<~SQL
      CREATE TABLE platform_events (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        event_id text NOT NULL,
        event_type text NOT NULL,
        schema_version integer DEFAULT 1,
        source text,
        anonymous_id text,
        session_id text,
        user_id bigint,
        company_id bigint,
        subject_type text,
        subject_id bigint,
        payload jsonb DEFAULT '{}',
        context jsonb DEFAULT '{}',
        occurred_at timestamptz NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now()
      ) PARTITION BY RANGE (occurred_at);

      CREATE INDEX idx_platform_events_type_time ON platform_events (event_type, occurred_at DESC);
      CREATE INDEX idx_platform_events_brin_time ON platform_events USING BRIN (occurred_at);
      CREATE INDEX idx_platform_events_event_id ON platform_events (event_id);

      CREATE OR REPLACE FUNCTION create_platform_events_partition(target_date timestamptz)
      RETURNS text AS $$
      DECLARE
          start_date timestamptz := date_trunc('month', target_date);
          end_date timestamptz := start_date + interval '1 month';
          partition_name text := 'platform_events_y' || to_char(start_date, 'YYYY') || 'm' || to_char(start_date, 'MM');
      BEGIN
          IF NOT EXISTS (
              SELECT 1 FROM pg_class c 
              JOIN pg_namespace n ON n.oid = c.relnamespace 
              WHERE c.relname = partition_name 
              AND n.nspname = ANY(current_schemas(false))
          ) THEN
              EXECUTE format('CREATE TABLE %I PARTITION OF platform_events FOR VALUES FROM (%L) TO (%L)', partition_name, start_date, end_date);
              RETURN partition_name;
          END IF;
          RETURN NULL;
      END;
      $$ LANGUAGE plpgsql;

      SELECT create_platform_events_partition(now());
      SELECT create_platform_events_partition(now() + interval '1 month');
      SELECT create_platform_events_partition(now() + interval '2 months');
    SQL
  end

  def down
    return unless ActiveRecord::Base.connection.adapter_name =~ /postgre/i
    drop_table :platform_events if table_exists?(:platform_events)
    execute "DROP FUNCTION IF EXISTS create_platform_events_partition(timestamptz)"
  end
end
